name: automatically deploy webpage

on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: copy code
        uses: actions/checkout@v4
            
      - name: initialise Github Pages environment
        uses: actions/configure-pages@v5

      - name: packing web file
        uses: actions/upload-pages-artifact@v3

      - name: publish
        uses: actions/deploy-pages@v4
