name: YAML Practice 3
on:
  push:
    branches: [main]

env:
  ProjectName: "My Web"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testing execution unit..."
  
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - run: echo "passing test, deploy now"
