name: YAML Practice 1
on:
  push:
    branches: [main]

env:
  ProjectName: "My Web"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Custom Message
        run: |
          echo "Project name: ${{ env.ProjectName }}"
          echo "User: ${{ github.actor }}"
