name: YAML Practice 2
on:
  push:
    branches: [main]

env:
  ProjectName: "My Web"

jobs:
  conditional-job:
    runs-on: ubuntu-latest
    steps:
      - name: only execute in main
        if: github.ref == 'refs/heads/main'
        run: echo "It is run in main"
      - name: execute in any branch
        run: echo "hello world"
